#!/usr/bin/env bash
# Generates docs/api-index.md: index of symbols exported by the Scheme
# modules vendored in docs/vendor/helix/*.scm.
#
# Extracted from: (provide ...), (define (name args...) ...),
# (define name ...), (define/contract ...).
# Arity is derived from the define header line (approximate).
# Idempotent and regenerable: ./scripts/gen-api-index.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR_HELIX="$ROOT/docs/vendor/helix"
OUT="$ROOT/docs/api-index.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

for f in "$VENDOR_HELIX"/*.scm; do
  mod="helix/$(basename "$f")"
  LC_ALL=C awk -v mod="$mod" '
    function setar(name, a) {
      # the rich define form overwrites the "?" set by an earlier provide
      if (a != "?" || !(name in ar)) ar[name] = a
    }
    function emit(name, a) { setar(name, a) }
    {
      line = $0
      i = index(line, ";")
      if (i > 0) line = substr(line, 1, i - 1)

      if (line ~ /^[ \t]*\(provide[ \t]/) {
        s = line
        sub(/^[ \t]*\(provide[ \t]+/, "", s)
        sub(/\)[ \t]*$/, "", s)
        if (s !~ /all-from-out/) {
          n = split(s, t, /[ \t]+/)
          for (k = 1; k <= n; k++) {
            gsub(/[()]/, "", t[k])
            if (t[k] != "") emit(t[k], "?")
          }
        }
      } else if (line ~ /^[ \t]*\((define|define\/contract)[^ \t)]*[ \t]*\(/) {
        s = line
        sub(/^[ \t]*\((define|define\/contract)[^ \t)]*[ \t]*\([ \t]*/, "", s)
        p = index(s, ")")
        args = (p > 0) ? substr(s, 1, p - 1) : s
        n = split(args, t, /[ \t]+/)
        if (n >= 1) {
          name = t[1]
          gsub(/[()]/, "", name)
          arity = 0
          optional = 0
          for (k = 2; k <= n; k++) {
            tag = t[k]
            gsub(/[()\[\]]/, "", tag)
            if (tag == "") continue
            if (t[k] ~ /^\[/) { optional++; continue }
            arity++
          }
          lbl = arity " args"
          if (optional > 0) lbl = arity "-" (arity + optional) " args (approx)"
          emit(name, lbl)
        }
      } else if (line ~ /^[ \t]*\((define|define\/contract)[ \t]+[^ \t(:]/) {
        s = line
        sub(/^[ \t]*\((define|define\/contract)[ \t]+/, "", s)
        n = split(s, t, /[ \t(]/)
        if (t[1] != "") emit(t[1], "?")
      }
    }
    END { for (name in ar) printf "%s\t%s\t%s\n", mod, name, ar[name] }
  ' "$f" >> "$TMP"
done

LC_ALL=C sort -t '	' -k1,1 -k2,2 -o "$TMP" "$TMP"

{
  echo "# Index of symbols — vendored helix/*.scm modules"
  echo
  echo "Generated by \`scripts/gen-api-index.sh\` — do not edit by hand."
  echo "Sources: \`docs/vendor/helix/*.scm\` (see docs/vendor/README.md)."
  echo "Arities are approximate: counted from the define header line;"
  echo "\"?\" = alias/re-export form, arity unknown (see the source .scm)."
  echo "Rust builtin modules (helix/core/text, helix/core/misc, ...) are"
  echo "not .scm files: the only references are docs/vendor/steel-docs.md."
  echo
  total=$(grep -c '	' -- "$TMP" || true)
  awk -F '	' '{print $1}' "$TMP" | sort -u | while read -r mod; do
    echo "### $mod"
    echo
    echo "| symbol | arity |"
    echo "|---|---|"
    awk -F '	' -v m="$mod" '$1 == m { printf "| %s | %s |\n", $2, $3 }' "$TMP"
    echo
  done
  echo "Total: $total symbols."
} > "$OUT"

rm -f "$TMP"
echo "Wrote $OUT ($(grep -c '^| [^|]' "$OUT" 2>/dev/null || echo 0) table rows)"
